### ISSUE TITLE
[Bug] The color table seems to be broken

### ISSUE THREAD

**Issue by Harshita-Kanal** [storybookjs/brand#17]
### Describe the bug

The color table on the Readme seems to be broken

### Steps to reproduce the behavior

1. Go to `README.md`
2. Scroll down to colors

### Screenshots and/or logs

![Capture1](https://user-images.githubusercontent.com/41537515/117223774-09bb5c80-ae2c-11eb-8630-186c7a923dbe.PNG)

### Environment

 - OS: Windows 10
 - Browser (if applicable): chrome

**Comment by ersel** [comment]
@Harshita-Kanal looks like the website used for images `https://placehold.it/15/2A0481/000000?text=+` have their SSL cert expired.

**Comment by ersel** [comment]
we could alternative use `https://via.placeholder.com/15.png/2A0481?text=%20`

**Comment by ndelangen** [comment]
Fixed it, thanks for the suggestion @ersel
